# -*- coding: utf-8 -*-
"""Render the CV PDF to page images the site can show inline.

A browser's own PDF viewer, dropped in through an iframe, arrives as a dark
grey panel that fights the page and does not render at all on iOS. Rendering
the pages here instead gives an embed that is part of the layout, needs no
JavaScript, and works everywhere. The PDF itself stays one click away.

    python _build/make_cv_preview.py

Writes static/img/cv/page-N.png and data/cv_pages.yaml. Re-run it whenever
static/files/choi-cv.pdf changes, or the page will keep showing the old CV.
"""
import hashlib
import io
import os
import sys

import fitz
from PIL import Image

sys.stdout.reconfigure(encoding='utf-8')

PDF = 'static/files/choi-cv.pdf'
OUT_DIR = 'static/img/cv'
DATA = 'data/cv_pages.yaml'
WIDTH = 1400          # source pixels; shown at ~820 CSS px, so ~1.7x density


def main():
    raw = open(PDF, 'rb').read()
    digest = hashlib.sha256(raw).hexdigest()[:12]
    doc = fitz.open(PDF)
    os.makedirs(OUT_DIR, exist_ok=True)

    for stale in os.listdir(OUT_DIR):
        if stale.startswith('page-') and stale.endswith('.png'):
            os.remove(os.path.join(OUT_DIR, stale))

    rows, total = [], 0
    for i, page in enumerate(doc, start=1):
        zoom = WIDTH / page.rect.width
        pm = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom))
        im = Image.frombytes('RGB', (pm.width, pm.height), pm.samples)
        # A CV is black on white; greyscale with a small palette holds the text
        # crisply at a third of the bytes of full-colour PNG.
        im = im.convert('L').convert('P', palette=Image.ADAPTIVE, colors=64)
        name = 'page-%d.png' % i
        path = os.path.join(OUT_DIR, name)
        im.save(path, 'PNG', optimize=True)
        n = os.path.getsize(path)
        total += n
        rows.append((name, pm.width, pm.height, n))
        print('  %s  %dx%d  %.0f KB' % (name, pm.width, pm.height, n / 1024))

    with open(DATA, 'w', encoding='utf-8', newline='\n') as f:
        f.write('# Generated by _build/make_cv_preview.py — do not edit by hand.\n')
        f.write('# Re-run that script after replacing static/files/choi-cv.pdf.\n')
        f.write('source_sha: %s\n' % digest)
        f.write('pdf_kb: %d\n' % round(len(raw) / 1024))
        f.write('count: %d\n' % len(rows))
        f.write('pages:\n')
        for name, w, h, _ in rows:
            f.write('  - file: img/cv/%s\n    width: %d\n    height: %d\n' % (name, w, h))

    print('%s  %d pages  %.0f KB of images  pdf sha %s'
          % (DATA, len(rows), total / 1024, digest))


if __name__ == '__main__':
    main()
